# Cloudflare Tunnel Configuration for Discord -> Notion Agent
# Reusing existing tunnel configuration
tunnel: e1439cb6-fd4e-4c3b-9bbb-c5dbc1f5273c
credentials-file: /etc/cloudflared/e1439cb6-fd4e-4c3b-9bbb-c5dbc1f5273c.json

ingress:
  # Discord -> Notion Agent endpoints
  - hostname: n8n.tzsmartsolutions.com
    path: /notion/*
    service: http://notion-agent:8000

  # Discord -> Notion Agent health check
  - hostname: n8n.tzsmartsolutions.com
    path: /health
    service: http://notion-agent:8000
    
  # Main agent endpoint (fallback for root requests)
  - hostname: n8n.tzsmartsolutions.com
    service: http://notion-agent:8000
    
  # Catch-all rule (REQUIRED as the last rule to avoid container restart issues)
  - service: http_status:404

# Logging configuration
logfile: /etc/cloudflared/cloudflared.log
loglevel: info 