# Cloudflare Tunnel Configuration for Discord -> Notion Agent
# Replace with your actual tunnel ID and credentials file path
tunnel: YOUR_TUNNEL_ID_HERE
credentials-file: /etc/cloudflared/YOUR_TUNNEL_ID_HERE.json

ingress:
  # Webhook endpoint exemption (to avoid 401 Unauthorized from Cloudflare Access)
  - hostname: YOUR_DOMAIN_HERE
    path: /webhook/*
    service: http://notion-agent:8080

  # Main agent endpoint
  - hostname: YOUR_DOMAIN_HERE
    service: http://notion-agent:8080
    
  # Health check endpoint (optional)
  - hostname: YOUR_DOMAIN_HERE
    path: /health
    service: http://notion-agent:8080
    
  # Catch-all rule (REQUIRED as the last rule to avoid container restart issues)
  - service: http_status:404

# Logging configuration
logfile: /etc/cloudflared/cloudflared.log
loglevel: info 